### ISSUE TITLE
New version has class loading issues or am i missing something?

### ISSUE THREAD

**Issue by MartijnSanders** [cosmocode/dokuwiki-plugin-oauthgeneric#5]
I am updating my small wiki to use the new oauth plugins. However when trying to login the user yields the following errors:

```
OAuth: login failed No such service generic
dokuwiki\plugin\oauth\Exception at /var/www/html/dokuwiki/lib/plugins/oauth/OAuthManager.php:271
#0 /var/www/html/dokuwiki/lib/plugins/oauth/OAuthManager.php(23): dokuwiki\plugin\oauth\OAuthManager->loadService()
#1 /var/www/html/dokuwiki/lib/plugins/oauth/action/login.php(66): dokuwiki\plugin\oauth\OAuthManager->startFlow()
#2 /var/www/html/dokuwiki/inc/Extension/EventHandler.php(81): action_plugin_oauth_login->handleStart()
#3 /var/www/html/dokuwiki/inc/Extension/Event.php(72): dokuwiki\Extension\EventHandler->process_event()
#4 /var/www/html/dokuwiki/inc/Extension/Event.php(128): dokuwiki\Extension\Event->advise_before()
#5 /var/www/html/dokuwiki/inc/Extension/Event.php(195): dokuwiki\Extension\Event->trigger()
#6 /var/www/html/dokuwiki/doku.php(116): dokuwiki\Extension\Event::createAndTrigger()
#7 {main}
```
i've added dblog statements to trace the location of the crash, which in the end seems to be the call to  class_exists($className) in registerService in ./vendor/lusitanian/oauth/src/OAuth/ServiceFactory.php. 
At this stage $className has the value dokuwiki\plugin\oauthgeneric\Generic.

Have copied the offended code into oauthgeneric\action.php and class_exists also does not work in that class. For good measure i also added a call 'class_exists($className, false)', which yields false. 

The Google adapter behaves in the same manner.  Does the new version have a class loading issue or am i missing something?

**Comment by MartijnSanders** [comment]
argh... i think it was typo on my behalf
